# Generated by Django 4.2.3 on 2023-07-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import inventory.middleware
import inventory.models.user
import inventory.utilities.db.hashfield
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='first name')),
                ('last_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='last name')),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(unique=True, verbose_name='Email Address')),
                ('email_hash', inventory.utilities.db.hashfield.HashField(max_length=125, unique=True, verbose_name='Email Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', inventory.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('handle', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('product_category', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('ST', 'Standard'), ('LF', 'Large Format'), ('HB', 'Half bottles'), ('WI', 'Wine')], default='ST', max_length=2)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('variant_sku', models.CharField(max_length=32)),
                ('variant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('variant_compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_src', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AC', 'Active'), ('DR', 'Draft'), ('AR', 'Archived')], default='AC', max_length=2, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuvee',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('vintage', models.CharField(blank=True, max_length=128, null=True)),
                ('alcohol_pct', models.SmallIntegerField(blank=True, null=True)),
                ('varietal', models.CharField(blank=True, max_length=128, null=True)),
                ('village', models.CharField(blank=True, max_length=128, null=True)),
                ('disgorgement', models.DateField(blank=True, null=True)),
                ('dosage', models.SmallIntegerField(blank=True, null=True)),
                ('see', models.CharField(blank=True, max_length=256, null=True)),
                ('smell', models.CharField(blank=True, max_length=256, null=True)),
                ('taste', models.CharField(blank=True, max_length=256, null=True)),
                ('pair', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('cell_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('created_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=inventory.middleware.get_api_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tried_cuvees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cuvee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
